### ISSUE TITLE
Release v0.3.0, v0.4.0

### ISSUE THREAD

**Issue by jbboehr** [jbboehr/php-psr#34]
I think we're way overdue for a release of 0.3.0. I think it should be safe to include #31 with my PHP5 compatibility changes.

@sergeyklay Is there anything you want in before release?

**Comment by jbboehr** [comment]
I guess it's technically bad form to add a feature after an RC, so I'll release a 0.4 with #31 after a final 0.3 release.

**Comment by sergeyklay** [comment]
@jbboehr I propose to release 0.3.0 version w/o new features (e.g. PSR-15 support). Then we can release  0.4.0, the latest release with PHP 5.x support (with mentioning this in release note) and with #31 plus PHP5 compatibility changes. In the 0.5.0 we cat safely drop the PHP 5.x support. What do you think about this?

**Comment by jbboehr** [comment]
Closed via d1b0420f0041b3ca01170b5065a52c6e141272d6
