### ISSUE TITLE
Auto detect .ini dir

### ISSUE THREAD

**Issue by dragoonis** [jbboehr/php-psr#42]
Hey,
I'm from PHP-FIG group.

I'm working on phalcon project with @sergeyklay. 
I'm integrating PSR-11 ContainerInterface .. I created this bash script to install `psr.so` ..

My question is .. I don't like how path to `conf.d` is hard coded .. do you have a good way to auto-detect this ?

```
#!/usr/bin/env bash
set -ex

apt-get update -y
apt-get install -y nano tree git gnupg gcc make re2c autoconf automake

mkdir -p /tmp/psr-ext-setup
cd /tmp/psr-ext-setup

rm -rf /tmp/psr-ext-setup/php-psr
git clone https://github.com/jbboehr/php-psr.git
cd php-psr
phpize
./configure
make
make test
make install
rm -rf /var/lib/apt/lists/*

echo extension=psr.so | tee -a /etc/php/7.1/cli/conf.d/psr.ini
php -m | grep psr


```

**Comment by jbboehr** [comment]
@dragoonis That's a pretty distribution-dependent question, no?

You could try getting the value of `Scan this dir for additional .ini files` out of `php -i`.

```
$ php -i | grep ini
Configuration File (php.ini) Path => /nix/store/1ip3r4rr646w3a658snrk638yd4vk159-php-7.1.11/lib
Scan this dir for additional .ini files => /etc/php.d
```

**Comment by sergeyklay** [comment]
I have an ugly approach:

```bash
PHP_CONFD=$(php --ini | \
    grep Additional | \
    awk -F'parsed:' '{print $2}' | \
    sed -r 's/,//g' | \
    tr -d '[:space:]')
```

**Comment by sergeyklay** [comment]
Or according to [`php_ini_scanned_files`](http://php.net/manual/en/function.php-ini-scanned-files.php):
```bash
php -r "echo dirname(explode(',', php_ini_scanned_files())[0]);"
```


but there is a potential issue:
> Returns a comma-separated string of .ini files on success. Each comma is followed by a newline. If the configure directive **--with-config-file-scan-dir** wasn't set and the `PHP_INI_SCAN_DIR` environment variable isn't set, **FALSE** is returned. 

I can't realize why it returns a comma-separated _string_ instead of array 🤦, but we can use this approach

**Comment by sergeyklay** [comment]
To use with php-config and configure directive `--with-config-file-scan-dir` is set:
```
$ php-config --configure-options | \
    tr -s ' ' '\n' | \
    grep -e '--with-config-file-scan-dir' | \
    cut -f2 -d=
```

**Comment by dragoonis** [comment]
That doesn't work inside a bash script, so I've modified it to look like this:

``` bash
VAL=$(
  echo `php-config --configure-options` | \
  tr -s ' ' '\n' | \
  grep -e '--with-config-file-scan-dir' \
  | cut -f2 -d=
)

echo "${VAL}"
```

**Comment by sergeyklay** [comment]
I think this may be closed

**Comment by jbboehr** [comment]
@sergeyklay Sounds good, thanks!
