### ISSUE TITLE
ServerRequestInterface not implements RequestInterface methods?

### ISSUE THREAD

**Issue by danielspk** [jbboehr/php-psr#49]
Hello, I am using the extension to use the PSR interfaces in a separate Zephir extension.

My method receives as a parameter a ServerRequestInterface and when invoking the method getUri() reports: **Class 'Psr\Http\Message\ServerRequestInterface' does not implement method: 'getUri'**

Example:

```zephir
public function handle(<ServerRequestInterface> request) -> <ResponseInterface> {
    // error:
    var_dump(request->getUri()->getPath());

    // ok:
    var requestBase;
    let requestBase = new RequestInterface();
    let requestBase = request;

    var_dump(requestBase->getUri()->getPath());
}
```

To solve this I must create a new variable of type RequestInterface to "convert" the type of object.

Do you know what may be happening?

Thank you

**Comment by jbboehr** [comment]
@danielspk Hey, looks like in this extension `ServerRequestInterface` isn't actually extending `RequestInterface`. I'll release a fix soon, thanks for letting me know!
