### ISSUE TITLE
Thank you from Phalcon

### ISSUE THREAD

**Issue by sergeyklay** [jbboehr/php-psr#59]
Hello @jbboehr, 

It's not a real issue. I just wanted to say you thanks and show you a page which says that we are dependent on php-psr extension: https://docs.phalconphp.com/4.0/en/installation

I think Phalcon is the first so large and public project requiring php-psr extension. 
Thank you helping us make Phalcon better.

P.S. Feel free to close this issue after reading

**Comment by jbboehr** [comment]
Thanks! Glad someone is getting some use out of it!
