### ISSUE TITLE
PSR v7.0 fails with "symbol lookup error"

### ISSUE THREAD

**Issue by swen100** [jbboehr/php-psr#71]
### System
* OpenSuse 15.1
* PHP 7.8 nts, no debug, Zend OPcache v7.3.8 enabled
### Problem
After compiling **master** or **v7.0** (from Github) I get the following errror:
```
php -v
php: symbol lookup error: /usr/local/lib64/extensions/no-debug-non-zts-20180731/psr.so: undefined symbol: zm_startup_psr_event_dispatcher
```
PHP gets unusable.
Btw: version 0.6.1 works fine!

**Comment by jbboehr** [comment]
@swen100 I double-checked the code and it looks okay - this could happen if you have a Makefile and object files from a previous version in your checkout. If this is the case, can you `phpize && ./configure && make clean` and try again?

**Comment by swen100** [comment]
U are right. I just removed the old directory, cloned it again and compiled it without any errors.
So: it works fine.
Thanks!
