### ISSUE TITLE
New release with PHP 8 support?

### ISSUE THREAD

**Issue by dzuelke** [jbboehr/php-psr#82]
Hi @jbboehr and others,

PHP 8.0.0 is getting really close and it looks like this extension supports it already.

All that's missing is a Git tag, and a release to PECL :)

Would be super if that could be done anytime soon so that e.g. PaaSes have a stable release version to provide to customers.

Thanks!

**Comment by jbboehr** [comment]
Done in https://github.com/jbboehr/php-psr/commit/43e21cc0bc727d8e1dea58e063a3bf02959467df !

**Comment by dzuelke** [comment]
Thanks!
