### ISSUE TITLE
Error with make when installing on macOS

### ISSUE THREAD

**Issue by akami-channel** [jbboehr/php-psr#83]
![Screen Shot 2021-01-11 at 5 52 30 PM](https://user-images.githubusercontent.com/52014815/104161740-b2395100-5436-11eb-8a2d-48340f774f5f.png)

Is this because I don't have the PHP development headers? I looked online but could not find those anywhere. I believe I installed php with brew.

**Comment by sergeyklay** [comment]
Yes, it is. You have to clone php source code and switch to relevant branch

**Comment by jbboehr** [comment]
I'm not a Mac guy, but I thought installing PHP through brew would usually install the PHP headers. Perhaps the brew install target isn't in the include path for some reason?

**Comment by akami-channel** [comment]
> Yes, it is. You have to clone php source code and switch to relevant branch

If I clone the php source code, how will the php-psr repo get access to the header files?

**Comment by akami-channel** [comment]
Are we sure it doesn't have something to do with the fact that /usr/include was removed in Catalina?
https://bbqsoftwares.com/blog/xdebug-catalina-issue

**Comment by sergeyklay** [comment]
You can easily append headers path to system one. Different compilers do it differently:

- clang: https://clang.llvm.org/docs/ClangCommandLineReference.html#include-path-management 
- gcc: https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html

Also take a look https://apple.stackexchange.com/a/372600/267719
