### ISSUE TITLE
Compatibility with psr/container 1.1

### ISSUE THREAD

**Issue by derrabus** [jbboehr/php-psr#84]
This extension currently breaks libraries that provide an implementation of `psr/container` 1.1, like Pimple 3.4 or Symfony DI 5.3.

### Example

**composer.json**

```json
{
    "require": {
        "psr/container": "^1.1"
    }
}
```

**MyContainer.php**

```php
<?php

use Psr\Container\ContainerInterface;

require __DIR__.'/vendor/autoload.php';

class MyContainer implements ContainerInterface
{
    public function has(string $id)
    {
        return false;
    }

    public function get(string $id)
    {
        throw new class extends \Exception implements NotFoundExceptionInterface {};
    }
}
```

**Output**
```
Fatal error: Declaration of MyContainer::get(string $id) must be compatible with Psr\Container\ContainerInterface::get($id) in /path/to/MyContainer.php on line 14
```

The script is executed correctly if I disable the `psr` extension.

**Comment by sergeyklay** [comment]
Is this works for you:
```json

{
    "require": {
        "ext-psr": "*"
    },
    "provide": {
        "psr/container": "^1"
    },
}
```

**Comment by derrabus** [comment]
@sergeyklay No, that would just uninstall the `psr/container` package.

**Comment by sergeyklay** [comment]
Well, as far as I know, this is usually what you should do anyway. Otherwise, you end up with two sources providing the same interface.

**Comment by jbboehr** [comment]
Kinda surprised they would change the interface in a non-major version. Looks like there's a 2.0 version out. I suppose we should update. Can you foresee any compatibility issues with phalcon @sergeyklay ?

**Comment by jbboehr** [comment]
Based on my reading of the mailing list at the time, it was my understanding that breaking interface changes would be published as a new library (e.g. psr/container2). It looks like they are not doing this.

**Comment by Jeckerson** [comment]
@jbboehr Could you create separate branch with updated interfraces so I could test it?

In case if this interfaces changes will break something from our side we will wait for new release from you. As we are almost ready to release Phalcon with PHP8 support: https://github.com/phalcon/cphalcon/pull/15287

**Comment by jbboehr** [comment]
Okay, I've opened #85 with psr/container@1.1.1

I also implemented 2.0 [[0]], but literally none of the libraries we test against are using it yet and it totally breaks them, so probably should hold off on that.

[0]: https://github.com/jbboehr/php-psr/tree/psr-container-2

**Comment by stof** [comment]
@jbboehr the change done in a minor version was perfectly valid, thanks to variance rules.

The issue is that enabling this extension ignores entirely the package requirements (as the interface at the version selected by composer won't be loaded at all).
This extension basically defeats any attempt of versioning the PSR packages.

**Comment by jbboehr** [comment]
> The issue is that enabling this extension ignores entirely the package requirements (as the interface at the version selected by composer won't be loaded at all).
This extension basically defeats any attempt of versioning the PSR packages.

This is just how extensions work and there is no resolution unless composer provides support for managing extensions. And well, I foolishly wasn't expecting there to ever be another version of a PSR without it being published as a new PSR in another namespace.
